apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
spec:
  selector:
    matchLabels:
      app: backend-service
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: backend-service
          image: minik_backend:v1
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP