apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: minik_web_app:v1
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: API_URL
              value: http://api.myapp.info